name : Second Example App
on : push
jobs:
   build_job:
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Execute Shell Script
        run: |
          chmod +x ./acsii-arwork.sh 
          ./acsii-arwork.sh
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact-file
          path: dragon.txt     
      - name: Sleep for 10 seconds
        run: sleep 10
   test_job:
     needs: build_job
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
            name: dragon-artifact-file
      - name: Test file
        run: |
          grep -i "dragon" dragon.txt
      - name: Sleep for 5 seconds
        run: sleep 5
   deploy_job:
     needs: test_job
     runs-on: ubuntu-latest
     steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
            name: dragon-artifact-file
      - name: Read file
        run:  cat dragon.txt