name : Third Example App
on :
 workflow_dispatch:
    inputs:
        logLevel:
         description: 'Log level'
         required: true
         default: 'warning'
         type: choice
         options:
          - info
          - warning
          - debug
        tags:
         description: 'Test scenario tags'
         required: false
         type: boolean
        environment:
         description: 'Environment to run tests against'
         type: environment
         required: true
env:
 DOCKER_URL: "docker.io"
 DOCKER_USERNAME: "aadidevopspro"
jobs:
   build_job:
     runs-on: ubuntu-latest
     steps:
       - name: Write Inputs
         run: echo ${{inputs.environment}} ${{inputs.logLevel}} ${{inputs.tags}}